mysql = [
    {host = "xxxx", user = "xxxx", db= "", password = "xxxxx", db_list = [
            xxxxx
        ]}
]
redis= [
    {host = "xxxx", user = "xxxx", db= "0", password = "xxx", db_list = [
            xxxx
        ]}
]
